resourcestring                                     {deutsch}

  capFCtime='Zeit seit Boot';
  hntFCtime='Zeit seit Boot vom Flight Controller (also seit der Kopter eingeschaltet worden war)';
  hntClose='Verbindung trennen und beenden';
  hntStatusBar='Number messages sent | Number messages received | Status';
  capTime='Time';
  hntTime='Datum/Zeit UTC aus Message SYSTEM_TIME (2)';
  capSatSNR='Signal-Rauschabstand';
  hntSatSNR='Signal-Rauschabstand der Satelliten  [dB]';
  capPolar='Azimuth and elevation of visible sats';
  hntPolar='Azimuth: Direction of satellite 0 to 360°, Elevation: 0 to 90° (0°: right on top of receiver, 90°: on the horizon)';
  capRecord='Record CSV';
  hntRecord='Record the received data messages to a CSV file in hexa-decimal format';
  capSensor='Create sensor file';
  hntSensor='Save received data messages to a binary file like Sensor files in flight logs';
  capSaveProt='&Save text';
  hntSaveProt='Save list of text messages to text file';
  hntPort='In case of connection Problems unplug and plug USB cable.'+lineending+
          'Double click to update port list.';
  capConnect='Connect';
  hntConnect='Connect to selected USB port';
  capDisConnect='Disconnect';
  hntDisConnect='Disonnect UART from USB port';
  hntSpeed='Select baud rate. Default 115200 shoult work for drone and camera.';
  capClose='Close';
  capSaveGUItext='&Text speichern';
  hntSaveGUItext='Save the text in the messages-window to a text file.';
  capCopySerial='Copy Vehicle ID';
  hntCopySerial='Copy Vehicle ID (serial number) to clipboard.';

  captsGUI='Act as H480 GUI replacement';
  captsYGC='Act as gimbal checker for CGO3+';
  captsFC='Act as flight controller to CGO3+ (Demo)';
  capSensorInfo='Sensor information';
  capGPSinfo='GNSS information';
  capSettings='System / Settings';
  msgPropellerRemoved='Ich habe alle Propeller abmontiert.';
  capEnableTesting='Testen erlauben';
  hntEnableTesting='Motoren nur ohne Propeller testen!';
  capLimitMsg='Zeilen auf 600 begrenzen';
  capHighRPM='Hohe RPM';
  hntHighRPM='Propellerdrehzahl auf 100 hochgesetzt. Vorsichtig damit umgehen!';
  hntGeoFence='Maximum distance from home point in Smart Mode.';
  hntHeightLimit='Maximum elevation above home point in Smart and Angle mode.';
  capGimbalCali='Gimbal calibration';
  hntGimbalCali='Gimbal calibration process like ST16 initiated.'+lineending+
                'Power cycle the camera once the calibration is finished.';
  hntGPS='Global Positioning System, originally NAVSTAR GPS';
  hntGLONASS='Глоба́льная навигацио́нная спу́тниковая систе́ма (ГЛОНА́СС)';
  hntSBAS='Satellite Based Augmentation System'+lineending+
          'A method of improving the navigation system''s attributes, such as precision, reliability, and availability.';
  capSystemTime='System time UTC';
  capNotUsed='Not used';
  hntNotUsed='Satellits not (yet) used for calculation of position';
  capSatUsed='Used for calculation';
  hntSatUsed='Satellits used for calculation of position';
  hntBoottime='Time since boot of the device';
  capVersion='SW versions';
  hntVersion='Read different software version from gimbal firmware';
  capYGC_Type='Show 2nd message';
  hntYGC_Type='Select which message you want to see in the second table.'+lineending+
              'Channel data will be empty in most cases. This is a special message.';
  hntPanelRight='Do gimbal calibration. Check manual. Process going from above to bottom.';
  capSerialNo='Serial number:';
  capCenter='Center';
  hntCenter='Set to neutral position';
  hntTiltControl='Camera tilt';
  hntTiltMode='Tilt mode: Angle / Velocity';
  hntPanMode='Pan mode: Follow / Pan controllable / Global';
  hntPanControl='Pan control';
  capTelemetry='Send test telemetry';
  hntTelemetry='Test telemetry messages over WiFi if received in Sensor files of flight logs.';

  rsSaved=' saved';
  rsDisconnected='Disconnected';
  rsConnected='Connected';
  rsEnabled='Enabled';
  rsAvailable='Available';
  rsNotMounted='Not mounted';
  rsInUse='satellites in use';
  rsVisible='satellites visible';
  rsConfirm='Please confirm';
  rsTime='Time';
  rsTimeUTC='System time UTC';
  rsSelected='selected';
  rsMotor='Motor';
  rsACW=' (A-CW)';
  rsBCCW=' (B-CCW)';
  rsFixType='Fix type';

  errSensorsNotHealthy='Sensors not healthy!';
  errNoUSBport='No USB port available';


